### PR TITLE
Added compression plugins: BandaiNamco and Konami variant 1

### PR DESCRIPTION
**Pull request by hansbonini**
Bandai Namco in Yu Yu Hakusho 2:
image

Konami Variant 1 in TMNT 4:
image

Only decompressors...

### CODE REVIEW

**Comment by Skarsnik** [comment]
You added generated file like .so and makefile :)

Le ven. 1 oct. 2021 à 12:24, Hans Bonini ***@***.***> a
écrit :

**Comment by hansbonini** [comment]
Sorry for the trash inside... let me clean...

**Comment by hansbonini** [comment]
Done

**Comment by Skarsnik** [comment]
Thanks for the new compression!

**Pull request merged**
